version: '3.7'
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/containers/nginx/Dockerfile
    volumes:
      - ${APP_PATH_HOST}:/var/www
    ports:
      - 8082:80
  php-fpm:
    build: ${CONTAINERS_PATH}/php-fpm
    volumes:
      - ${APP_PATH_HOST}:/var/www
      - ${DATA_PATH_HOST}/php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - DB_CONNECTION=pgsql
      ## mysql
#      - DB_PORT=3306
#      - DB_HOST=mysql
      ## pgsql
      - DB_PORT=5432
      - DB_HOST=pgsql
  php-cli:
    build: ${CONTAINERS_PATH}/php-cli
    volumes:
      - ${APP_PATH_HOST}:/var/www
      - ${DATA_PATH_HOST}/php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - DB_CONNECTION=pgsql
      ## mysql
#      - DB_PORT=3306
#      - DB_HOST=mysql
      ## pgsql
      - DB_PORT=5432
      - DB_HOST=pgsql
    tty: true
  mysql:
    image: mysql:5.7
    volumes:
      - ${STORAGE_PATH}/mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 33061:3306
  pgsql:
    image: postgres:9.6
    # image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DATABASE=${DB_NAME}
    ports:
      - 54321:5432
    volumes:
      - ${STORAGE_PATH}/postgres:/var/lib/postgresql/data
      - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
#      - ./storage/docker/postgres/:/var/lib/pgsql/9.5/data
#      - ./storage/docker/postgres/:/var/lib/pgsql/9.5
  redis:
    image: redis:3.0
    ports:
      - 63791:6379
  node:
    image: node:8.6-alpine
    volumes:
        - ${APP_PATH_HOST}:/var/www
    working_dir: /var/www
    tty: true
